runtime: nodejs22
env: standard

entrypoint: node src/server.js

handlers:
  # Untuk API routes
  - url: /api/.*
    script: auto

  # Untuk file statis, jika ada (sesuaikan jika Anda memiliki folder `public`)
  - url: /static
    static_dir: static

  # Default route
  - url: /.*
    script: auto

env_variables:
  PORT: 3000
  NODE_ENV: production
  SECRET_KEY: supersecretkey
  DB_NAME: nusatinggi_db
  DB_USER: root
  DB_PASSWORD: nusatinggi24
  DB_HOST: 34.101.47.182
  GOOGLE_APPLICATION_CREDENTIALS: serviceAccountKey.json

beta_settings:
  cloud_sql_instances: nusatinggi:asia-southeast2:nusatinggi-sql