runtime: nodejs22
env: standard

entrypoint: node src/server.js

handlers:
  # Untuk API routes
  - url: /api/.*
    script: auto

  # Untuk file statis, jika ada (sesuaikan jika Anda memiliki folder `public`)
  - url: /static
    static_dir: static

  # Default route
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production
  # Pastikan untuk menyertakan variabel lingkungan dari file .env Anda (jika ada)
  # DATABASE_URL: "your_database_url"
  # OTHER_ENV_VARIABLE: "value"